version: '2'
services:
  frontend:
    image: smspanel-frontend
    build: frontend
    environment:
      - BACKEND_URL=${BACKEND_URL}
      
  backend:
    image: smspanel-backend
    build: .
    environment:
      - API_USERNAME=${API_USERNAME}
      - API_PASSWORD=${API_PASSWORD}
      - CONTACTS_CSV=/contacts.csv
      - USERS=${USERS}
    volumes:
      - ${CONTACTS_FILE}:/contacts.csv
      
  proxy:
    image: smspanel-proxy
    build: nginx
    ports:
      - 80:80
